# Generated by Django 6.0.3 on 2026-03-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pphotos/%y/%m/%d')),
                ('technologies', models.CharField(help_text='فصل كل تقنية بفاصلة', max_length=250)),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
